sap.sap_operations collection content
sap-linuxlab/community.sap_operations pull request #14
Opened 2023-01-30 15:11 UTC by kksat

2023-01-30 15:37 UTC, kksat commented
@sean-freeman @rhmk @berndfinger @rainerleber 

I am waiting for your complete review and starting to answer comments after that.

Thank you

2023-01-30 16:40 UTC, rainerleber requested changes
first module checked see comments

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +  - module: sap.sap_operations.hana_backup
```suggestion
  - module: community.sap_operations.hana_backup
```

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +version_added: 1.1.0
```suggestion
version_added: 1.0.0
```

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
Must be apache with a exception to prevent lint fails

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +RETURN = r""" # """
should have a reutrn example like:

```
RETURN = r'''
query_result:
    description: List containing results of all queries executed (one sublist for every query).
    returned: on success
    type: list
    elements: list
```

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +  register: dir_instance
not part of the module it self

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +#!/usr/bin/python
does it really make sense to write a complete module for a few sql statements ? maybe it's less maintaining effort use the hdbsql module from sap_libs and write a role

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +  sap.sap_operations.hana_backup:
```suggestion
  community.sap_operations.hana_backup:
```

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +  sap.sap_operations.hana_backup:
```suggestion
  community.sap_operations.hana_backup:
```

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +  sap.sap_operations.hana_backup:
```suggestion
  community.sap_operations.hana_backup:
```

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +        ),
should be outsourced to a own var outside the module_args to be clearer

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +        ),
see: https://github.com/sap-linuxlab/community.sap_libs/blob/c4d27366c9b3b7f71f52409c25433f4f59c4843b/plugins/modules/sap_task_list_execute.py#L251 for example

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +        supports_check_mode=True,
it seams the module does not support a check mode

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +        instance_number=dict(type="str"),
required=true ?

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +        hdbsqluserstore_key=dict(type="str", no_log=False),
```suggestion
        hdbsqluserstore_key=dict(type="str"),
```
it's the default

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hana_backup.py
> +options:
each parameter should contain required except there is a default

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +#!/usr/bin/python
apache as above

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +  register: __DIR_EXECUTABLE
not part of the module

2023-01-30 16:40 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +# Run hdbsuserstore module with <hanasid>adm user with '-i' (interactive) flag like so
comments should not be part of the module

2023-02-01 08:56 UTC, rainerleber reviewed
hdbuserstore.py review

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +  sap.sap_operations.hdbuserstore:
```suggestion
  community.sap_operations.hdbuserstore:
```

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +  sap.sap_operations.hdbuserstore:
```suggestion
  community.sap_operations.hdbuserstore:
```

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +  register: __DIR_EXECUTABLE
i know it's an example to get the binary but it's against the good practice instead you should setup examples

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +  sap.sap_operations.hdbuserstore:
```suggestion
  community.sap_operations.hdbuserstore:
```

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +      Required only if you set new key, state=present
```suggestion
      Required only if you set new key, C(state=present)
```

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +    return rc == 0, stdout, {"key": key}
```suggestion
    return True, stdout, {"key": key}
```

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +    return rc == 0, stdout, {"key": key}
otherwise the rc is used as result['changed']  see line 265

2023-02-01 08:56 UTC, rainerleber commented on plugins/modules/hdbuserstore.py
> +    result.update(return_key)
what's the value of this command ? in my opinion line 262 or 265 should update the return_key

2023-05-11 13:37 UTC, rhmk commented on plugins/modules/hana_backup.py
> +# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
This is an important change GPL cannot be used

2023-05-11 13:42 UTC, rhmk reviewed
I basically agree to Rainers review from what I see. My biggest concern is the license incompatibility. Technically I suggest rejecting this particular PR and change the code with the renaming script/playbook to change from sap.sap_operations to community.sap_operations that Bernd uses to rename community to redhat. Then create a new PR that addresses the required changes from Rainer.

2023-05-11 13:42 UTC, rhmk reviewed
I basically agree to Rainers review from what I see. My biggest concern is the license incompatibility. Technically I suggest rejecting this particular PR and change the code with the renaming script/playbook to change from sap.sap_operations to community.sap_operations that Bernd uses to rename community to redhat. Then create a new PR that addresses the required changes from Rainer.

2024-07-21 14:23 UTC, sean-freeman commented
Closing this PR for the following reasons:

1. PR is a copy/paste without any integration
    - to existing Ansible Collection sap_libs for low-level Ansible Modules
    - to existing Ansible Roles within this Ansible Collection
    - it is not acceptable to "dump" code and other community members are expected to test/integrate
2. PR has no description of contents
3. PR has no waiver of GPL License from the rogue duplicate named sap_operations Ansible Collection. All code within SLL-OSI is Apache to facilitate business re-use, with a code-to-product strategy using standardised Community First approach; e.g. upstream > midstream (e.g. fork repo in 'redhat-sap' for productisation amendments) > downstream
4. PR review comments provided on same day as PR, were never addressed
5. PR has been waiting over a year for the above activities and there is clear lack of community spirit / unwillingness to collaborate

2024-07-21 14:23 UTC, closed without merging